import { copyFileSync, existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { feature, releaseFor, sha256 } from './main-adapter.mjs';

export const root = path.dirname(fileURLToPath(import.meta.url));
export const extensionFiles = Object.freeze([
  'task-box-core.js', 'task-box-coordinator.js', 'task-box-background.js',
  'task-box.js', 'task-box-worker.js', 'task-box-setup.html', 'task-box-setup.js'
]);
const inputFiles = [
  'feature.json', 'main-adapter.mjs', 'extension-adapter.mjs', 'loader.cjs', 'package.mjs',
  '../../scripts/rocaniiru-task-box-package.mjs', '../../scripts/macos-local-signing.mjs', '../../package-lock.json',
  'runtime/clear-service.ts', 'runtime/index.cjs', 'build-feature.mjs',
  ...extensionFiles.map(file => `extension/${file}`)
];

export function featureFingerprint() {
  return sha256(inputFiles.slice().sort().map(file => `${file}\0${sha256(readFileSync(path.join(root, file)))}\0`).join(''));
}

export function compatibilityScript(version) {
  const release = releaseFor(version);
  const contract = {
    appVersion: version, featureVersion: feature.featureVersion, protocol: feature.protocol,
    bridgeProtocol: release.bridgeProtocol, adapterRevision: feature.adapterRevision
  };
  return `// Generated by the patcher; do not edit.\nglobalThis.CLFTaskBoxCompatibility = Object.freeze(${JSON.stringify(contract)});\n`;
}

/** Emit only feature files. No official app, state, browser or extension lifecycle is touched. */
export function emitExtensionFeature(target, version) {
  releaseFor(version);
  mkdirSync(target, { recursive: true });
  for (const file of extensionFiles) copyFileSync(path.join(root, 'extension', file), path.join(target, file));
  writeFileSync(path.join(target, 'task-box-compatibility.js'), compatibilityScript(version));
}

export function emitRuntime(target) {
  mkdirSync(target, { recursive: true });
  // Compile this one independent module, not the application. TypeScript 7's supported CLI
  // is used rather than assuming the older transpileModule library API still exists.
  const compiler = path.resolve(root, '../../node_modules/typescript/bin/tsc');
  const output = spawnSync(process.execPath, [compiler, path.join(root, 'runtime/clear-service.ts'),
    '--ignoreConfig', '--target', 'ES2023', '--module', 'commonjs', '--strict', '--skipLibCheck',
    '--outDir', path.resolve(target)], { encoding: 'utf8' });
  if (output.error || output.status !== 0) throw new Error(`TASK_BOX_FEATURE_COMPILE_FAILED: ${output.stderr || output.stdout || output.error}`);
  renameSync(path.join(target, 'clear-service.js'), path.join(target, 'clear-service.cjs'));
  copyFileSync(path.join(root, 'runtime/index.cjs'), path.join(target, 'index.cjs'));
  copyFileSync(path.join(root, 'loader.cjs'), path.join(target, 'loader.cjs'));
}

export function buildFeature(target, version) {
  releaseFor(version);
  if (existsSync(target)) throw new Error('TASK_BOX_FEATURE_OUTPUT_EXISTS');
  const before = featureFingerprint();
  emitExtensionFeature(path.join(target, 'extension'), version);
  emitRuntime(path.join(target, 'runtime'));
  if (before !== featureFingerprint()) throw new Error('TASK_BOX_FEATURE_INPUT_CHANGED');
  const manifest = { schema: 1, featureVersion: feature.featureVersion, featureFingerprint: before,
    appVersion: version, protocol: feature.protocol, adapterRevision: feature.adapterRevision };
  writeFileSync(path.join(target, 'feature-build.json'), JSON.stringify(manifest, null, 2) + '\n');
  return manifest;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.slice(2).join(' ') !== '--development') throw new Error('Use --development; package builds call buildFeature explicitly.');
  const repo = path.resolve(root, '../..');
  const version = JSON.parse(readFileSync(path.join(repo, 'package.json'), 'utf8')).version;
  emitExtensionFeature(path.join(repo, 'extension'), version);
  console.log(`TASK_BOX_DEVELOPMENT_GENERATED feature=${feature.featureVersion} app=${version}; live_install_unchanged=true`);
}
